### ISSUE TITLE
how to compile this project in Visual Studio

### ISSUE THREAD

**Issue by william-vu** [spender-sandbox/cuckoomon-modified#28]
Hi, 
may I ask how to compile this using Visual studio C++? 
Thank,

**Comment by doomedraven** [comment]
https://github.com/spender-sandbox/cuckoomon-modified/issues/9

**Comment by spender-sandbox** [comment]
The current solution file I believe requires VS 2015, the community edition can be downloaded for free.

-Brad

**Comment by william-vu** [comment]
thanks. I will try this.

**Comment by william-vu** [comment]
Hi, 
is this dll project? and is there any (special) options that I need to pay attention when import this project?
thanks

**Comment by spender-sandbox** [comment]
The solution file contains projects for the loader executable and the DLL.  Building the solution will build both projects automatically.  Make sure the project types for both are set to "Release" instead of debug.

-Brad

**Comment by william-vu** [comment]
Hi Brad, 
I use VS 2015; Windows 8.1 to build the solution.  But I got errors like: cannot open include file "bson.h": no such file or directory. That's stranged because bson.h are in the folder bson already. Could you please tell me which could be the reason for this? 
Thanks

**Comment by doomedraven** [comment]
when you imported project it ask for install deps, did you install them?

**Comment by spender-sandbox** [comment]
If you're using the included solution/project files, the bson directory should be in the include path for all builds:
https://github.com/spender-sandbox/cuckoomon-modified/blob/MSVC/cuckoomon.vcxproj#L95

-Brad

**Comment by william-vu** [comment]
hi, 
I think the problem has been solved. The reason is I forgot to add the subfolder bson when import the code. 
Thanks for your help :)
