### ISSUE TITLE
lots of "Unable to hook" status on Windows 7 Guest OS

### ISSUE THREAD

**Issue by MerX1030** [spender-sandbox/cuckoomon-modified#3]
can't seem to find what might be the error.
hooks work fine on Windows XP Guest OS:
MD5 1929d5db340aac125c3dcbd4bb44202e
SHA1    0ab64275390b2deaf983d751f77f0f77014ef49a

**Comment by spender-sandbox** [comment]
Can you show me the analysis.log and give the hash of the DLLs involved?

**Comment by MerX1030** [comment]
Here are the logs and DLLs involved. (password is "cuckoo")
[cuckoo_logs.zip](https://github.com/spender-sandbox/cuckoomon-modified/files/168434/cuckoo_logs.zip)

In Windows XP there is a successful call to SHGetFolderPathW that was logged.
This call in Windows 7 was not logged and the logging ended prematurely.

**Comment by spender-sandbox** [comment]
The analysis.log wasn't included in the zip, can you show me that?  It's the only thing that would display which hooks failed.

-Brad

**Comment by MerX1030** [comment]
Here you go:
[windows7x86_analysis.log.txt](https://github.com/spender-sandbox/cuckoomon-modified/files/171406/windows7x86_analysis.log.txt)
[windowsxp_analysis.log.txt](https://github.com/spender-sandbox/cuckoomon-modified/files/171407/windowsxp_analysis.log.txt)

**Comment by spender-sandbox** [comment]
And these are pristine VM images?  You didn't install an AV product into them or something did you?  I don't see any reason for the hooks to have failed.

-Brad

**Comment by MerX1030** [comment]
Oooops. Sorry, my bad! Seems like I used the VM image with Endpoint Forensics.
Now closing this case.
