### ISSUE TITLE
Community signature Exception reported at offset 0x179de in cuckoomon

### ISSUE THREAD

**Issue by SeanKim777** [spender-sandbox/cuckoomon-modified#30]
Hi
Found signature message below:
Crashed cuckoomon during analysis. Report this error to the Github repo.
Exception reported at offset 0x179de in cuckoomon itself while accessing 0x1e0 from hook RtlDispatchException

OS: Windows 7 SP1
Sample zipped with password 'infected'

[user.php.zip](https://github.com/spender-sandbox/cuckoomon-modified/files/840249/user.php.zip)

**Comment by doomedraven** [comment]
crashes here too, but starts installer

**Comment by spender-sandbox** [comment]
Thanks, I'll take a look.

-Brad

**Comment by spender-sandbox** [comment]
There, should be fixed now (it's cerber btw).

-Brad
